sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in complex-k8s.json.enc -out complex-k8s.json -d
  - curl https://sdk.cloud.google.com > ./install.sh
  - bash ./install.sh --disable-prompts;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  ##- gcloud components install kubectl
  - gcloud --quiet components update
  - gcloud auth activate-service-account --key-file complex-k8s.json 
  - gcloud config set project complex-k8s-271814
  - gcloud config set compute/zone europe-west1-c
  - gcloud container clusters get-credentials complex-k8s-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t karakurty/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true karakurty/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh